name: devrantron # you probably want to 'snapcraft register <name>'
version: '1.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: An open source cross platform desktop application for devrant.io # 79 char long summary
description: Built with Electron and ReactJS, this is a application made for the community by the community.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  devrantron:
    command: electron/electron ./app/build/app.js
    plugs: [ "network", "x11", "opengl" ]

parts:
  build-devrantron:
    plugin: nil
    build-packages:
      - wget
      - zip
      - unzip
    build: |
        npm i
        npm i 7zip-bin-linux 
        npm run ci:build
        npm pack
        wget https://github.com/electron/electron/releases/download/v1.6.11/electron-v1.6.11-linux-x64.zip
        unzip *.zip -d electron
        mv electron ../install/electron
        tar -xvf *.tgz
        mv package/* ../install
    filesets:
       binaries:
        - ./*
    stage:
      - $binaries
    prime:
      - $binaries


